"""Standardised Approach default risk charge component."""

from frtb_common.attribution import AttributionMethod, CapitalContribution, ReconciliationStatus

from frtb_drc._version import __version__
from frtb_drc.adapters.arrow import (
    DRC_CTP_ARROW_COLUMN_SPECS,
    DRC_FAIR_VALUE_CAP_EVIDENCE_ARROW_COLUMN_SPECS,
    DRC_NONSEC_ARROW_COLUMN_SPECS,
    DRC_RISK_WEIGHT_EVIDENCE_ARROW_COLUMN_SPECS,
    DRC_SECURITISATION_NON_CTP_ARROW_COLUMN_SPECS,
    build_drc_ctp_batch_from_arrow,
    build_drc_ctp_risk_weight_evidence_from_arrow,
    build_drc_fair_value_cap_evidence_from_arrow,
    build_drc_nonsec_batch_from_arrow,
    build_drc_risk_weight_evidence_from_arrow,
    build_drc_securitisation_non_ctp_batch_from_arrow,
    build_drc_securitisation_non_ctp_risk_weight_evidence_from_arrow,
    normalize_drc_ctp_arrow_table,
    normalize_drc_fair_value_cap_evidence_arrow_table,
    normalize_drc_nonsec_arrow_table,
    normalize_drc_risk_weight_evidence_arrow_table,
    normalize_drc_securitisation_non_ctp_arrow_table,
)
from frtb_drc.adapters.positions import (
    build_drc_ctp_batch_from_columns,
    build_drc_nonsec_batch_from_columns,
    build_drc_nonsec_batch_from_positions,
    build_drc_securitisation_non_ctp_batch_from_columns,
)
from frtb_drc.assembly.hashes import (
    input_hash_for_drc_batch,
)
from frtb_drc.attribution import (
    DrcAttributionGrain,
    DrcAttributionSummary,
    calculate_drc_attribution,
    summarize_drc_attribution,
    summarize_drc_attribution_by_bucket,
    summarize_drc_attribution_by_category,
    summarize_drc_attribution_by_issuer,
    summarize_drc_attribution_by_risk_class,
    top_drc_attribution_summaries,
    validate_attribution_reconciliation,
)
from frtb_drc.audit import (
    input_snapshot_hash,
    result_json,
    rule_profile_hash,
    serialize_result,
    validate_reconciliation,
)
from frtb_drc.batch import (
    DrcBatchCapitalCalculation,
    DrcPositionBatch,
    calculate_drc_capital_from_batch,
)
from frtb_drc.capital import (
    CapitalInput,
    calculate_bucket_drc,
    calculate_category_drc,
    calculate_hedge_benefit_ratio,
)
from frtb_drc.component_summary import to_component_summary
from frtb_drc.crif import (
    DrcCrifAdapterResult,
    DrcCrifDirectionStrategy,
    DrcRejectedCrifRow,
    adapt_drc_crif_rows,
    drc_crif_result_to_arrow_tables,
)
from frtb_drc.data_models import (
    BranchMetadata,
    BranchType,
    BucketDrc,
    CategoryDrc,
    CreditQuality,
    DefaultDirection,
    DrcBucketType,
    DrcCalculationContext,
    DrcCapitalResult,
    DrcCitation,
    DrcFairValueCapEvidence,
    DrcFxConversion,
    DrcFxRate,
    DrcInstrumentType,
    DrcPosition,
    DrcRiskClass,
    DrcRiskWeightEvidence,
    DrcSeniority,
    DrcSourceLineage,
    GrossJtd,
    HedgeBenefitRatio,
    MaturityScaledJtd,
    NetJtd,
    RejectedOffset,
)
from frtb_drc.fair_value_cap import fair_value_cap_evidence_by_position
from frtb_drc.gross_jtd import calculate_gross_jtd, calculate_gross_jtds
from frtb_drc.impact import (
    DrcImpactAnalysis,
    DrcImpactMethod,
    DrcImpactRecord,
    calculate_drc_impact,
    validate_drc_impact_reconciliation,
)
from frtb_drc.kernel.ctp import (
    CtpCalculation,
    CtpCapitalInput,
    CtpNettingInput,
    calculate_ctp_category_drc,
    calculate_ctp_drc,
    calculate_ctp_gross_jtd,
    calculate_ctp_net_jtds,
    validate_ctp_context,
)
from frtb_drc.maturity import calculate_maturity_weight, scale_gross_jtd, scale_gross_jtds
from frtb_drc.netting import NettingInput, calculate_net_jtds
from frtb_drc.reference_data import (
    BucketDefinition,
    LgdRule,
    MaturityPolicy,
    RiskWeightRule,
    get_bucket_definition,
    get_lgd_rule,
    get_maturity_policy,
    get_risk_weight_rule,
    iter_bucket_definitions,
    iter_lgd_rules,
    iter_risk_weight_rules,
)
from frtb_drc.regimes import (
    BASEL_MAR22_PROFILE_ID,
    EU_CRR3_PROFILE_ID,
    PRA_UK_CRR_PROFILE_ID,
    US_NPR_2_0_PROFILE_ID,
    DrcProfileSupportCell,
    DrcRuleProfile,
    drc_profile_support_matrix,
    ensure_risk_class_supported,
    get_rule_profile,
    profile_content_hash,
)
from frtb_drc.risk_weight_evidence import risk_weight_evidence_by_position
from frtb_drc.scaffold import PACKAGE_METADATA, calculate_drc_capital
from frtb_drc.securitisation import (
    SecuritisationNonCtpCalculation,
    SecuritisationNonCtpCapitalInput,
    SecuritisationNonCtpNettingInput,
    calculate_securitisation_non_ctp_category_drc,
    calculate_securitisation_non_ctp_drc,
    calculate_securitisation_non_ctp_gross_jtd,
    calculate_securitisation_non_ctp_net_jtds,
    validate_securitisation_non_ctp_context,
)
from frtb_drc.validation import DrcInputError, validate_position, validate_positions

__all__ = [
    "BASEL_MAR22_PROFILE_ID",
    "DRC_CTP_ARROW_COLUMN_SPECS",
    "DRC_FAIR_VALUE_CAP_EVIDENCE_ARROW_COLUMN_SPECS",
    "DRC_NONSEC_ARROW_COLUMN_SPECS",
    "DRC_RISK_WEIGHT_EVIDENCE_ARROW_COLUMN_SPECS",
    "DRC_SECURITISATION_NON_CTP_ARROW_COLUMN_SPECS",
    "EU_CRR3_PROFILE_ID",
    "PACKAGE_METADATA",
    "PRA_UK_CRR_PROFILE_ID",
    "US_NPR_2_0_PROFILE_ID",
    "AttributionMethod",
    "BranchMetadata",
    "BranchType",
    "BucketDefinition",
    "BucketDrc",
    "CapitalContribution",
    "CapitalInput",
    "CategoryDrc",
    "CreditQuality",
    "CtpCalculation",
    "CtpCapitalInput",
    "CtpNettingInput",
    "DefaultDirection",
    "DrcAttributionGrain",
    "DrcAttributionSummary",
    "DrcBatchCapitalCalculation",
    "DrcBucketType",
    "DrcCalculationContext",
    "DrcCapitalResult",
    "DrcCitation",
    "DrcCrifAdapterResult",
    "DrcCrifDirectionStrategy",
    "DrcFairValueCapEvidence",
    "DrcFxConversion",
    "DrcFxRate",
    "DrcImpactAnalysis",
    "DrcImpactMethod",
    "DrcImpactRecord",
    "DrcInputError",
    "DrcInstrumentType",
    "DrcPosition",
    "DrcPositionBatch",
    "DrcProfileSupportCell",
    "DrcRejectedCrifRow",
    "DrcRiskClass",
    "DrcRiskWeightEvidence",
    "DrcRuleProfile",
    "DrcSeniority",
    "DrcSourceLineage",
    "GrossJtd",
    "HedgeBenefitRatio",
    "LgdRule",
    "MaturityPolicy",
    "MaturityScaledJtd",
    "NetJtd",
    "NettingInput",
    "ReconciliationStatus",
    "RejectedOffset",
    "RiskWeightRule",
    "SecuritisationNonCtpCalculation",
    "SecuritisationNonCtpCapitalInput",
    "SecuritisationNonCtpNettingInput",
    "__version__",
    "adapt_drc_crif_rows",
    "build_drc_ctp_batch_from_arrow",
    "build_drc_ctp_batch_from_columns",
    "build_drc_ctp_risk_weight_evidence_from_arrow",
    "build_drc_fair_value_cap_evidence_from_arrow",
    "build_drc_nonsec_batch_from_arrow",
    "build_drc_nonsec_batch_from_columns",
    "build_drc_nonsec_batch_from_positions",
    "build_drc_risk_weight_evidence_from_arrow",
    "build_drc_securitisation_non_ctp_batch_from_arrow",
    "build_drc_securitisation_non_ctp_batch_from_columns",
    "build_drc_securitisation_non_ctp_risk_weight_evidence_from_arrow",
    "calculate_bucket_drc",
    "calculate_category_drc",
    "calculate_ctp_category_drc",
    "calculate_ctp_drc",
    "calculate_ctp_gross_jtd",
    "calculate_ctp_net_jtds",
    "calculate_drc_attribution",
    "calculate_drc_capital",
    "calculate_drc_capital_from_batch",
    "calculate_drc_impact",
    "calculate_gross_jtd",
    "calculate_gross_jtds",
    "calculate_hedge_benefit_ratio",
    "calculate_maturity_weight",
    "calculate_net_jtds",
    "calculate_securitisation_non_ctp_category_drc",
    "calculate_securitisation_non_ctp_drc",
    "calculate_securitisation_non_ctp_gross_jtd",
    "calculate_securitisation_non_ctp_net_jtds",
    "drc_crif_result_to_arrow_tables",
    "drc_profile_support_matrix",
    "ensure_risk_class_supported",
    "fair_value_cap_evidence_by_position",
    "get_bucket_definition",
    "get_lgd_rule",
    "get_maturity_policy",
    "get_risk_weight_rule",
    "get_rule_profile",
    "input_hash_for_drc_batch",
    "input_snapshot_hash",
    "iter_bucket_definitions",
    "iter_lgd_rules",
    "iter_risk_weight_rules",
    "normalize_drc_ctp_arrow_table",
    "normalize_drc_fair_value_cap_evidence_arrow_table",
    "normalize_drc_nonsec_arrow_table",
    "normalize_drc_risk_weight_evidence_arrow_table",
    "normalize_drc_securitisation_non_ctp_arrow_table",
    "profile_content_hash",
    "result_json",
    "risk_weight_evidence_by_position",
    "rule_profile_hash",
    "scale_gross_jtd",
    "scale_gross_jtds",
    "serialize_result",
    "summarize_drc_attribution",
    "summarize_drc_attribution_by_bucket",
    "summarize_drc_attribution_by_category",
    "summarize_drc_attribution_by_issuer",
    "summarize_drc_attribution_by_risk_class",
    "to_component_summary",
    "top_drc_attribution_summaries",
    "validate_attribution_reconciliation",
    "validate_ctp_context",
    "validate_drc_impact_reconciliation",
    "validate_position",
    "validate_positions",
    "validate_reconciliation",
    "validate_securitisation_non_ctp_context",
]
