"""Standardised Approach default risk charge scaffold."""

from frtb_drc._version import __version__
from frtb_drc.arrow_handoff import (
    DRC_NONSEC_HANDOFF_COLUMN_SPECS,
    build_drc_nonsec_batch_from_handoff,
    normalize_drc_nonsec_arrow_table,
)
from frtb_drc.audit import (
    input_snapshot_hash,
    result_json,
    rule_profile_hash,
    serialize_result,
    validate_reconciliation,
)
from frtb_drc.batch import (
    DrcBatchCapitalCalculation,
    DrcPositionBatch,
    build_drc_nonsec_batch_from_columns,
    build_drc_nonsec_batch_from_positions,
    calculate_drc_capital_from_batch,
    input_hash_for_drc_batch,
)
from frtb_drc.capital import (
    CapitalInput,
    calculate_bucket_drc,
    calculate_category_drc,
    calculate_hedge_benefit_ratio,
)
from frtb_drc.data_models import (
    BranchMetadata,
    BranchType,
    BucketDrc,
    CategoryDrc,
    CreditQuality,
    DefaultDirection,
    DrcBucketType,
    DrcCalculationContext,
    DrcCapitalResult,
    DrcCitation,
    DrcFxConversion,
    DrcFxRate,
    DrcInstrumentType,
    DrcPosition,
    DrcRiskClass,
    DrcSeniority,
    DrcSourceLineage,
    GrossJtd,
    HedgeBenefitRatio,
    MaturityScaledJtd,
    NetJtd,
    RejectedOffset,
)
from frtb_drc.gross_jtd import calculate_gross_jtd, calculate_gross_jtds
from frtb_drc.maturity import calculate_maturity_weight, scale_gross_jtd, scale_gross_jtds
from frtb_drc.netting import NettingInput, calculate_net_jtds
from frtb_drc.reference_data import (
    BucketDefinition,
    LgdRule,
    MaturityPolicy,
    RiskWeightRule,
    get_bucket_definition,
    get_lgd_rule,
    get_maturity_policy,
    get_risk_weight_rule,
    iter_bucket_definitions,
    iter_lgd_rules,
    iter_risk_weight_rules,
)
from frtb_drc.regimes import (
    US_NPR_2_0_PROFILE_ID,
    DrcRuleProfile,
    ensure_risk_class_supported,
    get_rule_profile,
    profile_content_hash,
)
from frtb_drc.scaffold import PACKAGE_METADATA, calculate_drc_capital
from frtb_drc.validation import DrcInputError, validate_position, validate_positions

__all__ = [
    "DRC_NONSEC_HANDOFF_COLUMN_SPECS",
    "PACKAGE_METADATA",
    "US_NPR_2_0_PROFILE_ID",
    "BranchMetadata",
    "BranchType",
    "BucketDefinition",
    "BucketDrc",
    "CapitalInput",
    "CategoryDrc",
    "CreditQuality",
    "DefaultDirection",
    "DrcBatchCapitalCalculation",
    "DrcBucketType",
    "DrcCalculationContext",
    "DrcCapitalResult",
    "DrcCitation",
    "DrcFxConversion",
    "DrcFxRate",
    "DrcInputError",
    "DrcInstrumentType",
    "DrcPosition",
    "DrcPositionBatch",
    "DrcRiskClass",
    "DrcRuleProfile",
    "DrcSeniority",
    "DrcSourceLineage",
    "GrossJtd",
    "HedgeBenefitRatio",
    "LgdRule",
    "MaturityPolicy",
    "MaturityScaledJtd",
    "NetJtd",
    "NettingInput",
    "RejectedOffset",
    "RiskWeightRule",
    "__version__",
    "build_drc_nonsec_batch_from_columns",
    "build_drc_nonsec_batch_from_handoff",
    "build_drc_nonsec_batch_from_positions",
    "calculate_bucket_drc",
    "calculate_category_drc",
    "calculate_drc_capital",
    "calculate_drc_capital_from_batch",
    "calculate_gross_jtd",
    "calculate_gross_jtds",
    "calculate_hedge_benefit_ratio",
    "calculate_maturity_weight",
    "calculate_net_jtds",
    "ensure_risk_class_supported",
    "get_bucket_definition",
    "get_lgd_rule",
    "get_maturity_policy",
    "get_risk_weight_rule",
    "get_rule_profile",
    "input_hash_for_drc_batch",
    "input_snapshot_hash",
    "iter_bucket_definitions",
    "iter_lgd_rules",
    "iter_risk_weight_rules",
    "normalize_drc_nonsec_arrow_table",
    "profile_content_hash",
    "result_json",
    "rule_profile_hash",
    "scale_gross_jtd",
    "scale_gross_jtds",
    "serialize_result",
    "validate_position",
    "validate_positions",
    "validate_reconciliation",
]
