"""Credit Valuation Adjustment capital package."""

from frtb_cva._version import __version__
from frtb_cva.audit import input_hash, serialize_cva_result, validate_cva_result_reconciliation
from frtb_cva.ba_cva import (
    calculate_counterparty_standalone,
    calculate_netting_set_standalone,
    calculate_reduced_portfolio,
)
from frtb_cva.capital import calculate_cva_capital
from frtb_cva.data_models import (
    BaCvaCounterpartyCapital,
    BaCvaHedgeType,
    BaCvaNettingSetLine,
    BaCvaReducedPortfolioResult,
    BaCvaStandAloneLine,
    CreditQuality,
    CvaCalculationContext,
    CvaCapitalResult,
    CvaCitation,
    CvaCounterparty,
    CvaHedge,
    CvaMethod,
    CvaNettingSet,
    CvaRegulatoryProfile,
    CvaRunControls,
    CvaSector,
    CvaSourceLineage,
    HedgeEligibility,
    HedgeReferenceRelation,
    SaCvaBucketCapital,
    SaCvaRiskClass,
    SaCvaRiskClassCapital,
    SaCvaRiskFactorKey,
    SaCvaRiskMeasure,
    SaCvaSensitivity,
    SaCvaWeightedSensitivity,
    SensitivityTag,
)
from frtb_cva.numeric import is_reconciled
from frtb_cva.reference_data import (
    ba_cva_alpha,
    ba_cva_beta,
    ba_cva_discount_scalar,
    ba_cva_rho,
    ba_cva_risk_weight,
    compute_non_imm_discount_factor,
    girr_delta_intra_bucket_correlation,
    girr_delta_risk_weight,
    girr_delta_tenors,
    girr_inter_bucket_correlation,
    girr_specified_currencies,
)
from frtb_cva.regimes import CvaRuleProfile, get_cva_rule_profile, profile_content_hash
from frtb_cva.scope import ScopeResolution, resolve_calculation_method, validate_method_selection
from frtb_cva.scaffold import PACKAGE_METADATA
from frtb_cva.validation import (
    CvaInputError,
    normalise_ead_amount,
    normalise_sensitivity_amount,
    validate_calculation_context,
    validate_cva_counterparties,
    validate_cva_hedges,
    validate_cva_netting_sets,
    validate_sa_cva_sensitivities,
)

__all__ = [
    "BaCvaCounterpartyCapital",
    "BaCvaHedgeType",
    "BaCvaNettingSetLine",
    "BaCvaReducedPortfolioResult",
    "BaCvaStandAloneLine",
    "CreditQuality",
    "CvaCalculationContext",
    "CvaCapitalResult",
    "CvaCitation",
    "CvaCounterparty",
    "CvaHedge",
    "CvaInputError",
    "CvaMethod",
    "CvaNettingSet",
    "CvaRegulatoryProfile",
    "CvaRuleProfile",
    "CvaRunControls",
    "CvaSector",
    "CvaSourceLineage",
    "HedgeEligibility",
    "HedgeReferenceRelation",
    "PACKAGE_METADATA",
    "SaCvaBucketCapital",
    "SaCvaRiskClass",
    "SaCvaRiskClassCapital",
    "SaCvaRiskFactorKey",
    "SaCvaRiskMeasure",
    "SaCvaSensitivity",
    "SaCvaWeightedSensitivity",
    "ScopeResolution",
    "SensitivityTag",
    "__version__",
    "ba_cva_alpha",
    "ba_cva_beta",
    "ba_cva_discount_scalar",
    "ba_cva_rho",
    "ba_cva_risk_weight",
    "calculate_counterparty_standalone",
    "calculate_cva_capital",
    "calculate_netting_set_standalone",
    "calculate_reduced_portfolio",
    "compute_non_imm_discount_factor",
    "get_cva_rule_profile",
    "girr_delta_intra_bucket_correlation",
    "girr_delta_risk_weight",
    "girr_delta_tenors",
    "girr_inter_bucket_correlation",
    "girr_specified_currencies",
    "input_hash",
    "is_reconciled",
    "normalise_ead_amount",
    "normalise_sensitivity_amount",
    "profile_content_hash",
    "resolve_calculation_method",
    "serialize_cva_result",
    "validate_calculation_context",
    "validate_cva_counterparties",
    "validate_cva_hedges",
    "validate_cva_netting_sets",
    "validate_cva_result_reconciliation",
    "validate_method_selection",
    "validate_sa_cva_sensitivities",
]
