"""Shared unsupported-feature messages for CVA fail-closed gates."""

EXPOSURE_SENSITIVITY_GENERATION_POLICY = "EXPOSURE_SIMULATION_AND_SENSITIVITY_GENERATION"
MAR50_9_MATERIALITY_POLICY = "MAR50.9_MATERIALITY_THRESHOLD_CCR"
MAR50_9_UNSUPPORTED_MESSAGE = (
    "Materiality-threshold 100% CCR alternative (MAR50.9) is unsupported "
    "because frtb-cva does not own CCR capital inputs or orchestration method election."
)
SA_CVA_APPROVAL_GOVERNANCE_POLICY = "SA_CVA_APPROVAL_GOVERNANCE_WORKFLOW"

__all__ = [
    "EXPOSURE_SENSITIVITY_GENERATION_POLICY",
    "MAR50_9_MATERIALITY_POLICY",
    "MAR50_9_UNSUPPORTED_MESSAGE",
    "SA_CVA_APPROVAL_GOVERNANCE_POLICY",
]
