"""Standardised Approach residual risk add-on package."""

from frtb_rrao._version import __version__
from frtb_rrao.allocation import (
    SUPPORTED_RRAO_ALLOCATION_DIMENSIONS,
    build_rrao_allocation_report,
    build_rrao_allocation_reports,
    resolve_rrao_allocation_dimension,
    serialize_rrao_allocation_report,
    validate_rrao_allocation_report,
)
from frtb_rrao.audit import (
    input_hash_for_positions,
    serialize_rrao_result,
    validate_rrao_result_reconciliation,
)
from frtb_rrao.capital import build_rrao_capital_lines, build_rrao_subtotals, included_rrao_total
from frtb_rrao.classification import classify_rrao_position, classify_rrao_positions
from frtb_rrao.crif import (
    RraoAdapterResult,
    RraoAdapterWarning,
    RraoRejectedRow,
    adapt_crif_records,
    adapt_fnet_records,
    adapt_rrao_records,
)
from frtb_rrao.data_models import (
    RraoAllocationBucket,
    RraoAllocationDimension,
    RraoAllocationReport,
    RraoCalculationContext,
    RraoCapitalLine,
    RraoCapitalResult,
    RraoCitation,
    RraoClassification,
    RraoClassificationDecision,
    RraoEvidenceType,
    RraoExclusionReason,
    RraoInvestmentFundDescriptor,
    RraoInvestmentFundExposureType,
    RraoInvestmentFundMethod,
    RraoPosition,
    RraoRegulatoryProfile,
    RraoSourceLineage,
    RraoSubtotal,
)
from frtb_rrao.reference_data import (
    RraoEvidenceRule,
    RraoExclusionRule,
    RraoInvestmentFundRule,
    RraoRiskWeightRule,
    citations_for_profile,
    evidence_rule_for,
    evidence_rules_for_profile,
    exclusion_rule_for,
    exclusion_rules_for_profile,
    investment_fund_rule_for,
    investment_fund_rules_for_profile,
    risk_weight_rule_for,
    risk_weight_rules_for_profile,
)
from frtb_rrao.regimes import (
    RraoRuleProfile,
    get_rrao_rule_profile,
    profile_content_hash,
    resolve_rrao_profile,
)
from frtb_rrao.scaffold import PACKAGE_METADATA, calculate_rrao_capital
from frtb_rrao.validation import (
    RraoInputError,
    normalise_gross_effective_notional,
    validate_rrao_positions,
)

__all__ = [
    "PACKAGE_METADATA",
    "SUPPORTED_RRAO_ALLOCATION_DIMENSIONS",
    "RraoAdapterResult",
    "RraoAdapterWarning",
    "RraoAllocationBucket",
    "RraoAllocationDimension",
    "RraoAllocationReport",
    "RraoCalculationContext",
    "RraoCapitalLine",
    "RraoCapitalResult",
    "RraoCitation",
    "RraoClassification",
    "RraoClassificationDecision",
    "RraoEvidenceRule",
    "RraoEvidenceType",
    "RraoExclusionReason",
    "RraoExclusionRule",
    "RraoInputError",
    "RraoInvestmentFundDescriptor",
    "RraoInvestmentFundExposureType",
    "RraoInvestmentFundMethod",
    "RraoInvestmentFundRule",
    "RraoPosition",
    "RraoRegulatoryProfile",
    "RraoRejectedRow",
    "RraoRiskWeightRule",
    "RraoRuleProfile",
    "RraoSourceLineage",
    "RraoSubtotal",
    "__version__",
    "adapt_crif_records",
    "adapt_fnet_records",
    "adapt_rrao_records",
    "build_rrao_allocation_report",
    "build_rrao_allocation_reports",
    "build_rrao_capital_lines",
    "build_rrao_subtotals",
    "calculate_rrao_capital",
    "citations_for_profile",
    "classify_rrao_position",
    "classify_rrao_positions",
    "evidence_rule_for",
    "evidence_rules_for_profile",
    "exclusion_rule_for",
    "exclusion_rules_for_profile",
    "get_rrao_rule_profile",
    "included_rrao_total",
    "input_hash_for_positions",
    "investment_fund_rule_for",
    "investment_fund_rules_for_profile",
    "normalise_gross_effective_notional",
    "profile_content_hash",
    "resolve_rrao_allocation_dimension",
    "resolve_rrao_profile",
    "risk_weight_rule_for",
    "risk_weight_rules_for_profile",
    "serialize_rrao_allocation_report",
    "serialize_rrao_result",
    "validate_rrao_allocation_report",
    "validate_rrao_positions",
    "validate_rrao_result_reconciliation",
]
