from __future__ import annotations

import frtb_rrao

EXPECTED_PUBLIC_API = (
    "PACKAGE_METADATA",
    "RRAO_ARROW_COLUMN_SPECS",
    "SUPPORTED_RRAO_ALLOCATION_DIMENSIONS",
    "RraoAdapterResult",
    "RraoAdapterWarning",
    "RraoAllocationBucket",
    "RraoAllocationDimension",
    "RraoAllocationReport",
    "RraoBackToBackMatch",
    "RraoBatchCapitalCalculation",
    "RraoCalculationContext",
    "RraoCapitalLine",
    "RraoCapitalResult",
    "RraoCitation",
    "RraoClassification",
    "RraoClassificationDecision",
    "RraoEvidenceType",
    "RraoExclusionReason",
    "RraoInputError",
    "RraoInvestmentFundDescriptor",
    "RraoInvestmentFundExposureType",
    "RraoInvestmentFundMethod",
    "RraoPosition",
    "RraoPositionBatch",
    "RraoRegulatoryProfile",
    "RraoRejectedRow",
    "RraoRuleProfile",
    "RraoSourceLineage",
    "RraoSubtotal",
    "__version__",
    "adapt_crif_records",
    "adapt_fnet_records",
    "adapt_rrao_records",
    "build_rrao_allocation_report",
    "build_rrao_allocation_reports",
    "build_rrao_batch_from_arrow",
    "build_rrao_batch_from_columns",
    "build_rrao_batch_from_positions",
    "calculate_rrao_capital",
    "calculate_rrao_capital_from_batch",
    "classify_rrao_position",
    "classify_rrao_positions",
    "get_rrao_rule_profile",
    "input_hash_for_positions",
    "input_hash_for_rrao_batch",
    "normalize_rrao_arrow_table",
    "resolve_rrao_allocation_dimension",
    "serialize_rrao_allocation_report",
    "serialize_rrao_result",
    "to_component_summary",
    "validate_rrao_allocation_report",
    "validate_rrao_positions",
    "validate_rrao_result_reconciliation",
)


def test_top_level_public_api_surface_is_explicit_and_narrow() -> None:
    assert frtb_rrao.__all__ == list(EXPECTED_PUBLIC_API)
    assert len(frtb_rrao.__all__) < 57
