"""Generate or verify the package status dashboard from the maturity registry."""

from __future__ import annotations

import argparse
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = Path("docs/quality/package_maturity.toml")
DEFAULT_OUTPUT = Path("docs/quality/PACKAGE_STATUS.md")
CROSSWALK_DIR = ROOT / "docs" / "regulatory" / "crosswalk"


@dataclass(frozen=True)
class RequiredTest:
    id: str
    path: Path


@dataclass(frozen=True)
class PackageEntry:
    package: str
    import_name: str
    maturity: str
    component_type: str
    metadata_object: str | None
    calculation_entrypoint: str | None
    required_tests: tuple[RequiredTest, ...]


@dataclass(frozen=True)
class Registry:
    packages: tuple[PackageEntry, ...]


def load_registry(registry_path: Path = REGISTRY_PATH, *, root: Path = ROOT) -> Registry:
    data = tomllib.loads((root / registry_path).read_text(encoding="utf-8"))
    packages: list[PackageEntry] = []
    for raw_package in data.get("packages", []):
        raw_tests = raw_package.get("required_tests", [])
        required_tests = tuple(
            RequiredTest(id=str(entry["id"]), path=Path(str(entry["path"])))
            for entry in raw_tests
            if isinstance(entry, dict)
        )
        packages.append(
            PackageEntry(
                package=str(raw_package["package"]),
                import_name=str(raw_package["import_name"]),
                maturity=str(raw_package["maturity"]),
                component_type=str(raw_package["component_type"]),
                metadata_object=raw_package.get("metadata_object"),
                calculation_entrypoint=raw_package.get("calculation_entrypoint"),
                required_tests=required_tests,
            )
        )
    return Registry(packages=tuple(packages))


@dataclass(frozen=True)
class CrosswalkSummary:
    """Requirement crosswalk coverage for one capital component."""

    path: Path
    requirement_count: int
    source_ref_count: int


def crosswalk_summary(import_name: str) -> CrosswalkSummary | None:
    """Return crosswalk coverage for a package import name when present."""

    path = CROSSWALK_DIR / f"{import_name.replace('_', '-')}.yml"
    if not path.exists():
        return None

    text = path.read_text(encoding="utf-8")
    requirement_count = text.count("\n  - id:")
    source_ref_count = text.count("\n      - ")
    return CrosswalkSummary(
        path=path.relative_to(ROOT / "docs"),
        requirement_count=requirement_count,
        source_ref_count=source_ref_count,
    )


def _format_required_tests(entry: PackageEntry) -> str:
    if not entry.required_tests:
        return "—"
    return ", ".join(
        f"`{test.id}` (`{test.path}`)" for test in sorted(entry.required_tests, key=lambda t: t.id)
    )


def _format_optional(value: str | None) -> str:
    return f"`{value}`" if value else "—"


def render_dashboard(*, root: Path = ROOT) -> str:
    """Render markdown for all registry packages."""

    registry = load_registry(REGISTRY_PATH, root=root)
    lines = [
        "# Package status dashboard",
        "",
        "Generated from [`package_maturity.toml`](package_maturity.toml) and the",
        "regulatory requirement crosswalk files under [`../regulatory/crosswalk/`]",
        "(../regulatory/crosswalk/). Do not edit this file by hand.",
        "",
        "Regenerate or verify with:",
        "",
        "```bash",
        "make package-status-dashboard",
        "```",
        "",
        "| Package | Import | Maturity | Component | Metadata | Entrypoint |",
        "| Required tests | Crosswalk |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]

    for entry in sorted(registry.packages, key=lambda item: item.package):
        crosswalk = crosswalk_summary(entry.import_name)
        if crosswalk is None:
            crosswalk_cell = "—"
        else:
            link_path = Path("..") / crosswalk.path
            crosswalk_cell = (
                f"{crosswalk.requirement_count} requirements, "
                f"{crosswalk.source_ref_count} source refs "
                f"([`{crosswalk.path.name}`]({link_path.as_posix()}))"
            )
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{entry.package}`",
                    f"`{entry.import_name}`",
                    f"`{entry.maturity}`",
                    f"`{entry.component_type}`",
                    _format_optional(entry.metadata_object),
                    _format_optional(entry.calculation_entrypoint),
                    _format_required_tests(entry),
                    crosswalk_cell,
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Maturity legend",
            "",
            "| Maturity | Meaning |",
            "| --- | --- |",
            "| `implemented` | Deterministic public calculation path with validation evidence |",
            "| `partial_runtime` | Supported runtime slice with explicit fail-closed paths |",
            "| `orchestration_partial` | Suite handoff contracts without full aggregation |",
            "| `result_store_partial` | Storage contracts with a local DuckDB/Parquet backend |",
            "| `shared` | Shared library, not a capital component |",
            "",
            "Outputs from this suite are prototype model-validation evidence, not final",
            "regulatory capital.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Dashboard markdown path relative to the repository root.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the output file matches generated content instead of writing it.",
    )
    args = parser.parse_args(argv)

    rendered = render_dashboard()
    output_path = ROOT / args.output

    if args.check:
        if not output_path.exists():
            print(f"ERROR: missing dashboard file: {output_path}", file=sys.stderr)
            return 1
        existing = output_path.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"ERROR: {output_path} is stale; run `make package-status-dashboard`",
                file=sys.stderr,
            )
            return 1
        print(f"package status dashboard: ok ({output_path})")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
