from __future__ import annotations

from pathlib import Path

from scripts.ci import generate_package_status_dashboard as dashboard


def test_render_dashboard_includes_registry_packages() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    rendered = dashboard.render_dashboard(root=repo_root)

    assert "| `frtb-ima` |" in rendered
    assert "| `frtb-drc` |" in rendered
    assert "`partial_runtime`" in rendered
    assert "Do not edit this file by hand." in rendered


def test_check_mode_passes_for_committed_dashboard() -> None:
    assert dashboard.main(["--check"]) == 0
