"""NMRF stress artifact conversion and generation support gates."""

from __future__ import annotations

import numpy as np

from frtb_ima.data_models import LiquidityHorizon
from frtb_ima.expected_shortfall import expected_shortfall
from frtb_ima.nmrf_types import (
    _NMRF_MINIMUM_LIQUIDITY_HORIZON,
    _UNSUPPORTED_GENERATION_FEATURES,
    NMRFStressArtifact,
    NMRFStressMethod,
    NMRFStressScenarioResult,
)
from frtb_ima.regimes import (
    RegulatoryPolicy,
    RegulatoryRegime,
    UnsupportedRegulatoryFeature,
)


def nmrf_effective_liquidity_horizon(
    risk_factor_liquidity_horizon: LiquidityHorizon,
) -> LiquidityHorizon:
    """Return the NMRF stress horizon after applying the 20-day floor.
    Parameters
    ----------
    risk_factor_liquidity_horizon : LiquidityHorizon
        Risk factor liquidity horizon.

    Returns
    -------
    LiquidityHorizon
        Result of the operation.
    """
    if not isinstance(risk_factor_liquidity_horizon, LiquidityHorizon):
        raise TypeError("risk_factor_liquidity_horizon must be a LiquidityHorizon")
    if risk_factor_liquidity_horizon.value < _NMRF_MINIMUM_LIQUIDITY_HORIZON.value:
        return _NMRF_MINIMUM_LIQUIDITY_HORIZON
    return risk_factor_liquidity_horizon


def ses_for_nmrf_linear(sensitivity: float, shock: float) -> float:
    """Compute the SES contribution for a single NMRF using a linear approximation.

    SES_i = |sensitivity_i| * shock_i

    Args:
        sensitivity: First-order sensitivity (dollar P&L per unit of risk factor move).
        shock:       Stress shock size (in risk factor units, positive).

    Returns:
        SES contribution as a positive scalar.
    Parameters
    ----------
    sensitivity : float
        Sensitivity.
    shock : float
        Shock.

    Returns
    -------
    float
        Result of the operation.
    """
    return abs(sensitivity) * abs(shock)


def nmrf_stress_result_from_linear_sensitivity(
    risk_factor_name: str,
    sensitivity: float,
    shock: float,
    *,
    source: str = "",
    notes: str = "Linear sensitivity approximation generated by frtb-ima.",
) -> NMRFStressScenarioResult:
    """Build an individual NMRF SES result from the linear approximation helper.

    This is not a full regulatory direct/stepwise/full-revaluation stress
    scenario. It is retained as a transparent approximation for tests and demos.
    Parameters
    ----------
    risk_factor_name : str
        Risk factor name.
    sensitivity : float
        Sensitivity.
    shock : float
        Shock.
    source : str, optional
        Source.
    notes : str, optional
        Notes.

    Returns
    -------
    NMRFStressScenarioResult
        Result of the operation.
    """
    return NMRFStressScenarioResult(
        risk_factor_name=risk_factor_name,
        method=NMRFStressMethod.LINEAR_SENSITIVITY,
        ses=ses_for_nmrf_linear(sensitivity, shock),
        generated_by_prototype=True,
        source=source,
        notes=notes,
    )


def nmrf_stress_result_from_external_ses(
    risk_factor_name: str,
    ses: float,
    method: NMRFStressMethod,
    *,
    source: str,
    notes: str = "",
) -> NMRFStressScenarioResult:
    """Record an externally supplied NMRF SES value and its upstream method.

    This lets the capital layer consume risk-engine direct, stepwise, or
    full-revaluation outputs without pretending this package generated them.
    Parameters
    ----------
    risk_factor_name : str
        Risk factor name.
    ses : float
        Ses.
    method : NMRFStressMethod
        Method.
    source : str
        Source.
    notes : str, optional
        Notes.

    Returns
    -------
    NMRFStressScenarioResult
        Result of the operation.
    """
    return NMRFStressScenarioResult(
        risk_factor_name=risk_factor_name,
        method=method,
        ses=float(ses),
        generated_by_prototype=False,
        source=source,
        notes=notes,
    )


def require_nmrf_stress_generation_supported(
    method: NMRFStressMethod,
    policy: RegulatoryPolicy | None = None,
) -> None:
    """Raise a named unsupported-feature error for unimplemented SES generation.

    This package can generate only the linear-sensitivity approximation. Direct,
    stepwise, and full-revaluation methods are valid upstream methods to record
    via ``nmrf_stress_result_from_external_ses`` but are not generated here.
    Parameters
    ----------
    method : NMRFStressMethod
        Method.
    policy : RegulatoryPolicy | None, optional
        Policy.
    """
    if method == NMRFStressMethod.LINEAR_SENSITIVITY:
        return
    feature_name = _UNSUPPORTED_GENERATION_FEATURES[method]
    regime = policy.regime if policy is not None else RegulatoryRegime.FED_NPR_2_0
    raise UnsupportedRegulatoryFeature(
        regime,
        feature_name,
        "NMRF stress-scenario generation",
    )


def calculate_nmrf_ses_from_revaluation(
    artifact: NMRFStressArtifact,
    policy: RegulatoryPolicy,
    *,
    allow_linear_approximation: bool = False,
) -> NMRFStressScenarioResult:
    """Extract one NMRF SES value from an upstream revaluation loss vector.

    The vector is expected to be a post-valuation artifact, not a pricing model
    embedded in the capital layer. ES can be negative if every scenario is a
    gain, so SES is floored at zero. ``MAX_LOSS_FALLBACK`` artifacts use the
    maximum supplied loss instead of a tail average.
    Parameters
    ----------
    artifact : NMRFStressArtifact
        Artifact.
    policy : RegulatoryPolicy
        Policy.
    allow_linear_approximation : bool, optional
        Allow linear approximation.

    Returns
    -------
    NMRFStressScenarioResult
        Result of the operation.
    """
    if artifact.method == NMRFStressMethod.LINEAR_SENSITIVITY and not allow_linear_approximation:
        raise ValueError(
            "LINEAR_SENSITIVITY artifacts are approximation-only and require "
            "allow_linear_approximation=True"
        )

    if artifact.method == NMRFStressMethod.MAX_LOSS_FALLBACK:
        ses = max(0.0, float(np.max(artifact.losses)))
    else:
        ses = max(
            0.0,
            expected_shortfall(
                artifact.losses,
                alpha=policy.es_confidence_level,
                estimator=policy.es_estimator,
            ),
        )
    return NMRFStressScenarioResult(
        risk_factor_name=artifact.risk_factor_name,
        method=artifact.method,
        ses=ses,
        generated_by_prototype=artifact.generated_by_prototype,
        source=artifact.source,
        notes=artifact.notes,
    )


__all__ = [
    "calculate_nmrf_ses_from_revaluation",
    "nmrf_effective_liquidity_horizon",
    "nmrf_stress_result_from_external_ses",
    "nmrf_stress_result_from_linear_sensitivity",
    "require_nmrf_stress_generation_supported",
    "ses_for_nmrf_linear",
]
