"""
Non-Modellable Risk Factor (NMRF) Stressed Expected Shortfall (SES).

NPR 2.0 profile mechanics:

    - Type A NMRFs: included in both IMCC and SES.
    - Type B NMRFs: included in SES only, with a policy-supplied partial-correlation parameter.

Aggregation formulas used here:

    Type A SES (zero correlation under the NPR 2.0 proposed formula):
        SES_A_term = sum(SES_i^2 for i in Type_A)

    Type B SES (partial correlation via rho parameter):
        SES_B_term =
            rho    * (sum(SES_i))^2
            + (1 - rho) * sum(SES_i^2)

    Combined SES:
        SES = sqrt(SES_A_term + SES_B_term)

The capital layer consumes direct, stepwise, full-revaluation, or max-loss
fallback stress artifacts produced by an upstream valuation run. It validates
those artifacts, extracts vectorized SES values, routes Type A / Type B NMRFs,
and aggregates capital. The labelled linear / sensitivity-based helper remains
an explicit approximation for tests and demos only.

Regulatory traceability:
    Basel MAR33 NMRF stress-scenario capital; U.S. NPR 2.0 SES treatment for
    Type A / Type B NMRFs; EU CRR Article 325bk. See
    docs/REGULATORY_TRACEABILITY.md.
"""

from __future__ import annotations

import logging
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from enum import StrEnum

import numpy as np
import numpy.typing as npt

from frtb_ima.data_models import LiquidityHorizon, ModellabilityStatus
from frtb_ima.expected_shortfall import expected_shortfall
from frtb_ima.logging import calculation_log_extra
from frtb_ima.regimes import (
    RegulatoryPolicy,
    RegulatoryRegime,
    TypeASESAggregationMode,
    UnsupportedRegulatoryFeature,
)


class NMRFStressMethod(StrEnum):
    """Method used to produce an individual NMRF stress scenario SES value."""

    LINEAR_SENSITIVITY = "LINEAR_SENSITIVITY"
    DIRECT = "DIRECT"
    STEPWISE = "STEPWISE"
    FULL_REVALUATION = "FULL_REVALUATION"
    MAX_LOSS_FALLBACK = "MAX_LOSS_FALLBACK"


_UNSUPPORTED_GENERATION_FEATURES: dict[NMRFStressMethod, str] = {
    NMRFStressMethod.DIRECT: "nmrf_direct_stress_scenario_generation",
    NMRFStressMethod.STEPWISE: "nmrf_stepwise_stress_scenario_generation",
    NMRFStressMethod.FULL_REVALUATION: "nmrf_full_revaluation_stress_scenario_generation",
    NMRFStressMethod.MAX_LOSS_FALLBACK: "nmrf_max_loss_fallback_generation",
}

_NMRF_MINIMUM_LIQUIDITY_HORIZON = LiquidityHorizon.LH20
logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class NMRFStressScenarioResult:
    """
    Individual NMRF stress scenario result consumed by SES aggregation.

    ``generated_by_prototype`` is retained for API compatibility and flags
    approximation-only artifacts generated by this package. Direct, stepwise,
    and full-revaluation losses must come from upstream stress artifacts rather
    than embedded pricing logic in this package.
    """

    risk_factor_name: str
    method: NMRFStressMethod
    ses: float
    generated_by_prototype: bool
    source: str = ""
    notes: str = ""

    def __post_init__(self) -> None:
        if not self.risk_factor_name:
            raise ValueError("risk_factor_name must be non-empty")
        if not isinstance(self.method, NMRFStressMethod):
            raise TypeError("method must be an NMRFStressMethod")
        if not math.isfinite(self.ses) or self.ses < 0.0:
            raise ValueError(f"ses must be a non-negative finite value, got {self.ses}")

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails."""
        return {
            "risk_factor_name": self.risk_factor_name,
            "method": self.method.value,
            "ses": self.ses,
            "generated_by_prototype": self.generated_by_prototype,
            "source": self.source,
            "notes": self.notes,
        }


@dataclass(frozen=True)
class NMRFStressArtifact:
    """
    Post-valuation NMRF stress output consumed by the capital layer.

    The capital layer does not price trades. It validates and consumes loss
    vectors produced by an upstream valuation run under the selected NMRF stress
    method. Values use the package loss convention: positive means loss,
    negative means gain.
    """

    risk_factor_name: str
    method: NMRFStressMethod
    losses: npt.NDArray[np.float64] | Sequence[float]
    liquidity_horizon: LiquidityHorizon
    stress_period: str
    source: str
    scenario_ids: tuple[str, ...] = ()
    generated_by_prototype: bool = False
    notes: str = ""

    def __post_init__(self) -> None:
        if not self.risk_factor_name:
            raise ValueError("risk_factor_name must be non-empty")
        if not isinstance(self.method, NMRFStressMethod):
            raise TypeError("method must be an NMRFStressMethod")
        if not isinstance(self.liquidity_horizon, LiquidityHorizon):
            raise TypeError("liquidity_horizon must be a LiquidityHorizon")
        if self.liquidity_horizon.value < _NMRF_MINIMUM_LIQUIDITY_HORIZON.value:
            raise ValueError("NMRF liquidity_horizon must be at least 20 business days")
        if not self.stress_period:
            raise ValueError("stress_period must be non-empty")
        if not self.source:
            raise ValueError("source must be non-empty")

        losses = _as_loss_array(self.losses, "losses")
        scenario_ids = tuple(self.scenario_ids)
        if scenario_ids:
            if len(scenario_ids) != losses.size:
                raise ValueError("scenario_ids length must match losses length")
            if any(not scenario_id for scenario_id in scenario_ids):
                raise ValueError("scenario_ids cannot contain empty values")
            if len(scenario_ids) != len(set(scenario_ids)):
                raise ValueError("scenario_ids contains duplicates")

        object.__setattr__(self, "losses", losses)
        object.__setattr__(self, "scenario_ids", scenario_ids)

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable audit summary without expanding the loss vector."""
        return {
            "risk_factor_name": self.risk_factor_name,
            "method": self.method.value,
            "loss_count": int(np.asarray(self.losses).size),
            "liquidity_horizon": self.liquidity_horizon.value,
            "stress_period": self.stress_period,
            "source": self.source,
            "generated_by_prototype": self.generated_by_prototype,
            "notes": self.notes,
        }


@dataclass(frozen=True)
class SESAggregationResult:
    """Audit-friendly decomposition of NMRF SES aggregation."""

    type_a_count: int
    type_b_count: int
    type_a_sum_of_squares: float
    type_b_correlated_term: float
    type_b_sum_of_squares: float
    type_b_linear_sum: float
    type_b_rho: float
    total_ses: float

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails."""
        return {
            "type_a_count": self.type_a_count,
            "type_b_count": self.type_b_count,
            "type_a_sum_of_squares": self.type_a_sum_of_squares,
            "type_b_correlated_term": self.type_b_correlated_term,
            "type_b_sum_of_squares": self.type_b_sum_of_squares,
            "type_b_linear_sum": self.type_b_linear_sum,
            "type_b_rho": self.type_b_rho,
            "total_ses": self.total_ses,
        }


@dataclass(frozen=True)
class NMRFCapitalRouting:
    """Risk-factor routing implied by Fed NPR 2.0 Type A / Type B treatment."""

    modellable_risk_factors: tuple[str, ...]
    type_a_nmrf_risk_factors: tuple[str, ...]
    type_b_nmrf_risk_factors: tuple[str, ...]
    imcc_risk_factors: tuple[str, ...]
    ses_risk_factors: tuple[str, ...]

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails."""
        return {
            "modellable_risk_factors": list(self.modellable_risk_factors),
            "type_a_nmrf_risk_factors": list(self.type_a_nmrf_risk_factors),
            "type_b_nmrf_risk_factors": list(self.type_b_nmrf_risk_factors),
            "imcc_risk_factors": list(self.imcc_risk_factors),
            "ses_risk_factors": list(self.ses_risk_factors),
        }


@dataclass(frozen=True)
class NMRFCapitalResult:
    """NMRF SES result with routing and aggregation audit detail."""

    routing: NMRFCapitalRouting
    type_a_results: tuple[NMRFStressScenarioResult, ...]
    type_b_results: tuple[NMRFStressScenarioResult, ...]
    aggregation: SESAggregationResult

    @property
    def total_ses(self) -> float:
        """Total SES scalar used by the models-based capital formula."""
        return self.aggregation.total_ses

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails."""
        return {
            "routing": self.routing.as_dict(),
            "type_a_results": [result.as_dict() for result in self.type_a_results],
            "type_b_results": [result.as_dict() for result in self.type_b_results],
            "aggregation": self.aggregation.as_dict(),
            "total_ses": self.total_ses,
        }


def _as_loss_array(
    values: Sequence[float] | npt.NDArray[np.float64],
    name: str,
) -> npt.NDArray[np.float64]:
    arr = np.asarray(values, dtype=float)
    if arr.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")
    if arr.size == 0:
        raise ValueError(f"{name} must be non-empty")
    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{name} must contain only finite values")
    result = arr.astype(np.float64, copy=True)
    result.flags.writeable = False
    return result


def _as_abs_ses_array(
    values: Sequence[float] | npt.NDArray[np.float64],
    name: str,
) -> npt.NDArray[np.float64]:
    arr = np.asarray(values, dtype=float)
    if arr.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")
    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{name} must contain only finite values")
    return np.abs(arr.astype(np.float64, copy=False))


def nmrf_effective_liquidity_horizon(
    risk_factor_liquidity_horizon: LiquidityHorizon,
) -> LiquidityHorizon:
    """Return the NMRF stress horizon after applying the 20-day floor."""
    if not isinstance(risk_factor_liquidity_horizon, LiquidityHorizon):
        raise TypeError("risk_factor_liquidity_horizon must be a LiquidityHorizon")
    if risk_factor_liquidity_horizon.value < _NMRF_MINIMUM_LIQUIDITY_HORIZON.value:
        return _NMRF_MINIMUM_LIQUIDITY_HORIZON
    return risk_factor_liquidity_horizon


def ses_for_nmrf_linear(sensitivity: float, shock: float) -> float:
    """
    Compute the SES contribution for a single NMRF using a linear approximation.

    SES_i = |sensitivity_i| * shock_i

    Args:
        sensitivity: First-order sensitivity (dollar P&L per unit of risk factor move).
        shock:       Stress shock size (in risk factor units, positive).

    Returns:
        SES contribution as a positive scalar.
    """
    return abs(sensitivity) * abs(shock)


def nmrf_stress_result_from_linear_sensitivity(
    risk_factor_name: str,
    sensitivity: float,
    shock: float,
    *,
    source: str = "",
    notes: str = "Linear sensitivity approximation generated by frtb-ima.",
) -> NMRFStressScenarioResult:
    """
    Build an individual NMRF SES result from the linear approximation helper.

    This is not a full regulatory direct/stepwise/full-revaluation stress
    scenario. It is retained as a transparent approximation for tests and demos.
    """
    return NMRFStressScenarioResult(
        risk_factor_name=risk_factor_name,
        method=NMRFStressMethod.LINEAR_SENSITIVITY,
        ses=ses_for_nmrf_linear(sensitivity, shock),
        generated_by_prototype=True,
        source=source,
        notes=notes,
    )


def nmrf_stress_result_from_external_ses(
    risk_factor_name: str,
    ses: float,
    method: NMRFStressMethod,
    *,
    source: str,
    notes: str = "",
) -> NMRFStressScenarioResult:
    """
    Record an externally supplied NMRF SES value and its upstream method.

    This lets the capital layer consume risk-engine direct, stepwise, or
    full-revaluation outputs without pretending this package generated them.
    """
    return NMRFStressScenarioResult(
        risk_factor_name=risk_factor_name,
        method=method,
        ses=float(ses),
        generated_by_prototype=False,
        source=source,
        notes=notes,
    )


def require_nmrf_stress_generation_supported(
    method: NMRFStressMethod,
    policy: RegulatoryPolicy | None = None,
) -> None:
    """
    Raise a named unsupported-feature error for unimplemented SES generation.

    This package can generate only the linear-sensitivity approximation. Direct,
    stepwise, and full-revaluation methods are valid upstream methods to record
    via ``nmrf_stress_result_from_external_ses`` but are not generated here.
    """
    if method == NMRFStressMethod.LINEAR_SENSITIVITY:
        return
    feature_name = _UNSUPPORTED_GENERATION_FEATURES[method]
    regime = policy.regime if policy is not None else RegulatoryRegime.FED_NPR_2_0
    raise UnsupportedRegulatoryFeature(
        regime,
        feature_name,
        "NMRF stress-scenario generation",
    )


def calculate_nmrf_ses_from_revaluation(
    artifact: NMRFStressArtifact,
    policy: RegulatoryPolicy,
    *,
    allow_linear_approximation: bool = False,
) -> NMRFStressScenarioResult:
    """
    Extract one NMRF SES value from an upstream revaluation loss vector.

    The vector is expected to be a post-valuation artifact, not a pricing model
    embedded in the capital layer. ES can be negative if every scenario is a
    gain, so SES is floored at zero. ``MAX_LOSS_FALLBACK`` artifacts use the
    maximum supplied loss instead of a tail average.
    """
    if artifact.method == NMRFStressMethod.LINEAR_SENSITIVITY and not allow_linear_approximation:
        raise ValueError(
            "LINEAR_SENSITIVITY artifacts are approximation-only and require "
            "allow_linear_approximation=True"
        )

    if artifact.method == NMRFStressMethod.MAX_LOSS_FALLBACK:
        ses = max(0.0, float(np.max(artifact.losses)))
    else:
        ses = max(
            0.0,
            expected_shortfall(
                artifact.losses,
                alpha=policy.es_confidence_level,
                estimator=policy.es_estimator,
            ),
        )
    return NMRFStressScenarioResult(
        risk_factor_name=artifact.risk_factor_name,
        method=artifact.method,
        ses=ses,
        generated_by_prototype=artifact.generated_by_prototype,
        source=artifact.source,
        notes=artifact.notes,
    )


def ses_values_from_stress_results(
    results: Sequence[NMRFStressScenarioResult],
) -> tuple[float, ...]:
    """Extract SES values from individual NMRF stress scenario results."""
    return tuple(result.ses for result in results)


def aggregate_ses_type_a(values: Sequence[float] | npt.NDArray[np.float64]) -> float:
    """
    Aggregate SES contributions for Type A NMRFs.

    The NPR 2.0 proposed SES formula aggregates Type A NMRFs with zero
    correlation, so the Type A-only component is the square root of the sum of
    squared individual SES values.
    """
    abs_vals = _as_abs_ses_array(values, "values")
    return float(math.sqrt(np.dot(abs_vals, abs_vals)))


def aggregate_ses_type_b(
    values: Sequence[float] | npt.NDArray[np.float64],
    rho: float,
) -> float:
    """
    Aggregate SES contributions for Type B NMRFs.

    Partial correlation via rho, supplied by the applicable policy:

        SES_B = sqrt(rho * (sum SES_i)^2 + (1 - rho) * sum(SES_i^2))

    Args:
        values: Individual SES contributions (positive scalars).
        rho:    Correlation parameter. 0 = fully diversified, 1 = fully correlated.
    """
    if not (0.0 <= rho <= 1.0):
        raise ValueError(f"rho must be in [0, 1], got {rho}")

    abs_vals = _as_abs_ses_array(values, "values")
    if abs_vals.size == 0:
        return 0.0
    linear_sum = float(np.sum(abs_vals))
    sum_of_squares = float(np.dot(abs_vals, abs_vals))

    return math.sqrt(rho * linear_sum**2 + (1.0 - rho) * sum_of_squares)


def aggregate_ses_breakdown(
    type_a_values: Sequence[float] | npt.NDArray[np.float64],
    type_b_values: Sequence[float] | npt.NDArray[np.float64],
    type_b_rho: float,
) -> SESAggregationResult:
    """
    Compute total SES from Type A and Type B NMRF contributions with decomposition.

    Proposed U.S. NPR 2.0 SES formula implemented here:

        SES = sqrt(
            sum(Type_A_SES_i^2)
            + rho * (sum(Type_B_SES_i))^2
            + (1 - rho) * sum(Type_B_SES_i^2)
        )
    """
    if not (0.0 <= type_b_rho <= 1.0):
        raise ValueError(f"type_b_rho must be in [0, 1], got {type_b_rho}")

    type_a = _as_abs_ses_array(type_a_values, "type_a_values")
    type_b = _as_abs_ses_array(type_b_values, "type_b_values")

    type_a_sum_of_squares = float(np.dot(type_a, type_a))
    type_b_sum_of_squares = float(np.dot(type_b, type_b))
    type_b_linear_sum = float(np.sum(type_b))
    type_b_correlated_term = (
        type_b_rho * type_b_linear_sum**2 + (1.0 - type_b_rho) * type_b_sum_of_squares
    )
    total = math.sqrt(type_a_sum_of_squares + type_b_correlated_term)

    return SESAggregationResult(
        type_a_count=int(type_a.size),
        type_b_count=int(type_b.size),
        type_a_sum_of_squares=type_a_sum_of_squares,
        type_b_correlated_term=type_b_correlated_term,
        type_b_sum_of_squares=type_b_sum_of_squares,
        type_b_linear_sum=type_b_linear_sum,
        type_b_rho=type_b_rho,
        total_ses=total,
    )


def aggregate_ses_breakdown_for_policy(
    type_a_values: Sequence[float] | npt.NDArray[np.float64],
    type_b_values: Sequence[float] | npt.NDArray[np.float64],
    policy: RegulatoryPolicy,
) -> SESAggregationResult:
    """Compute decomposed SES using policy parameters and taxonomy support gates."""
    policy.require_capital_runtime_supported()
    if policy.uses_type_a_type_b_taxonomy:
        policy.require_type_a_type_b_taxonomy()
        if (
            policy.type_a_ses_aggregation_mode
            != TypeASESAggregationMode.ZERO_CORRELATION_ROOT_SUM_SQUARES
        ):
            raise ValueError(
                "NPR 2.0 policy must use zero-correlation root-sum-square aggregation "
                "for Type A SES"
            )
        return aggregate_ses_breakdown(
            type_a_values,
            type_b_values,
            type_b_rho=policy.type_b_ses_rho,
        )
    return aggregate_ses_breakdown(
        type_a_values,
        type_b_values,
        type_b_rho=0.0,
    )


def aggregate_ses(
    type_a_values: Sequence[float] | npt.NDArray[np.float64],
    type_b_values: Sequence[float] | npt.NDArray[np.float64],
    type_b_rho: float,
) -> float:
    """Return total SES from Type A and Type B NMRF contributions."""
    return aggregate_ses_breakdown(
        type_a_values,
        type_b_values,
        type_b_rho=type_b_rho,
    ).total_ses


def aggregate_ses_for_policy(
    type_a_values: Sequence[float] | npt.NDArray[np.float64],
    type_b_values: Sequence[float] | npt.NDArray[np.float64],
    policy: RegulatoryPolicy,
) -> float:
    """
    Aggregate SES using policy parameters.

    This wrapper is only valid for policies that support the U.S. NPR
    Type A / Type B split. EU and UK profiles currently use broader NMRF
    terminology, so this wrapper raises a named unsupported-feature error.
    """
    return aggregate_ses_breakdown_for_policy(
        type_a_values,
        type_b_values,
        policy,
    ).total_ses


def _validate_classification_mapping(
    classifications: Mapping[str, ModellabilityStatus],
) -> None:
    if not classifications:
        raise ValueError("classifications must be non-empty")
    for risk_factor_name, status in classifications.items():
        if not risk_factor_name:
            raise ValueError("classification risk-factor names must be non-empty")
        if not isinstance(status, ModellabilityStatus):
            raise TypeError("classification values must be ModellabilityStatus")


def route_nmrf_classifications_for_capital(
    classifications: Mapping[str, ModellabilityStatus],
    policy: RegulatoryPolicy,
) -> NMRFCapitalRouting:
    """
    Route RFET classifications into IMCC and SES populations.

    Under the Fed NPR 2.0 profile, Type A NMRFs remain in IMCC and also
    require SES. Type B NMRFs require SES only. Under UK CRR / EU comparison
    profiles, modellable factors stay in IMCC and all NMRF statuses feed SES only.
    """
    policy.require_capital_runtime_supported()
    _validate_classification_mapping(classifications)

    modellable: list[str] = []
    type_a: list[str] = []
    type_b: list[str] = []
    for risk_factor_name, status in classifications.items():
        if status == ModellabilityStatus.MODELLABLE:
            modellable.append(risk_factor_name)
        elif status == ModellabilityStatus.TYPE_A_NMRF:
            type_a.append(risk_factor_name)
        elif status == ModellabilityStatus.TYPE_B_NMRF:
            type_b.append(risk_factor_name)

    modellable = sorted(modellable)
    type_a = sorted(type_a)
    type_b = sorted(type_b)

    if policy.uses_type_a_type_b_taxonomy:
        policy.require_type_a_type_b_taxonomy()
        imcc_risk_factors = tuple(modellable + type_a)
    else:
        imcc_risk_factors = tuple(modellable)

    return NMRFCapitalRouting(
        modellable_risk_factors=tuple(modellable),
        type_a_nmrf_risk_factors=tuple(type_a),
        type_b_nmrf_risk_factors=tuple(type_b),
        imcc_risk_factors=imcc_risk_factors,
        ses_risk_factors=tuple(type_a + type_b),
    )


def _artifact_by_risk_factor(
    artifacts: Sequence[NMRFStressArtifact],
) -> dict[str, NMRFStressArtifact]:
    result: dict[str, NMRFStressArtifact] = {}
    for artifact in artifacts:
        if artifact.risk_factor_name in result:
            raise ValueError(f"duplicate NMRF stress artifact for {artifact.risk_factor_name}")
        result[artifact.risk_factor_name] = artifact
    return result


def _validate_required_artifacts(
    routing: NMRFCapitalRouting,
    classifications: Mapping[str, ModellabilityStatus],
    artifacts_by_name: Mapping[str, NMRFStressArtifact],
    required_methods: Mapping[str, NMRFStressMethod] | None,
    required_liquidity_horizons: Mapping[str, LiquidityHorizon] | None,
) -> None:
    classification_names = set(classifications)
    unknown = [
        risk_factor_name
        for risk_factor_name in artifacts_by_name
        if risk_factor_name not in classification_names
    ]
    if unknown:
        raise ValueError(f"NMRF stress artifacts reference unknown risk factors: {unknown}")

    modellable_artifacts = [
        risk_factor_name
        for risk_factor_name in artifacts_by_name
        if classifications[risk_factor_name] == ModellabilityStatus.MODELLABLE
    ]
    if modellable_artifacts:
        raise ValueError(
            "NMRF stress artifacts were supplied for modellable risk factors: "
            f"{modellable_artifacts}"
        )

    missing = [
        risk_factor_name
        for risk_factor_name in routing.ses_risk_factors
        if risk_factor_name not in artifacts_by_name
    ]
    if missing:
        raise ValueError(f"Missing NMRF stress artifacts for: {missing}")

    if required_methods is not None:
        for risk_factor_name in routing.ses_risk_factors:
            expected_method = required_methods.get(risk_factor_name)
            if expected_method is not None:
                actual_method = artifacts_by_name[risk_factor_name].method
                if actual_method != expected_method:
                    raise ValueError(
                        f"NMRF artifact method mismatch for {risk_factor_name}: "
                        f"expected {expected_method.value}, got {actual_method.value}"
                    )

    if required_liquidity_horizons is not None:
        for risk_factor_name in routing.ses_risk_factors:
            required_lh = required_liquidity_horizons.get(risk_factor_name)
            if required_lh is not None:
                actual_lh = artifacts_by_name[risk_factor_name].liquidity_horizon
                if actual_lh.value < required_lh.value:
                    raise ValueError(
                        f"NMRF artifact liquidity horizon too short for {risk_factor_name}: "
                        f"required at least {required_lh.value}, got {actual_lh.value}"
                    )


def calculate_nmrf_capital_for_policy(
    classifications: Mapping[str, ModellabilityStatus],
    artifacts: Sequence[NMRFStressArtifact],
    policy: RegulatoryPolicy,
    *,
    required_methods: Mapping[str, NMRFStressMethod] | None = None,
    required_liquidity_horizons: Mapping[str, LiquidityHorizon] | None = None,
    allow_linear_approximation: bool = False,
    run_id: str | None = None,
    desk_id: str | None = None,
) -> NMRFCapitalResult:
    """
    Validate NMRF stress artifacts, extract SES, and aggregate Type A / Type B.

    Missing Type A or Type B stress artifacts are hard errors. This prevents the
    capital layer from silently falling back to the linear approximation helper.
    """
    policy.require_capital_runtime_supported()
    routing = route_nmrf_classifications_for_capital(classifications, policy)
    artifacts_by_name = _artifact_by_risk_factor(tuple(artifacts))
    _validate_required_artifacts(
        routing,
        classifications,
        artifacts_by_name,
        required_methods,
        required_liquidity_horizons,
    )

    type_a_results = tuple(
        calculate_nmrf_ses_from_revaluation(
            artifacts_by_name[risk_factor_name],
            policy,
            allow_linear_approximation=allow_linear_approximation,
        )
        for risk_factor_name in routing.type_a_nmrf_risk_factors
    )
    type_b_results = tuple(
        calculate_nmrf_ses_from_revaluation(
            artifacts_by_name[risk_factor_name],
            policy,
            allow_linear_approximation=allow_linear_approximation,
        )
        for risk_factor_name in routing.type_b_nmrf_risk_factors
    )
    aggregation = aggregate_ses_breakdown_for_policy(
        ses_values_from_stress_results(type_a_results),
        ses_values_from_stress_results(type_b_results),
        policy,
    )
    result = NMRFCapitalResult(
        routing=routing,
        type_a_results=type_a_results,
        type_b_results=type_b_results,
        aggregation=aggregation,
    )
    logger.info(
        "nmrf_capital_complete",
        extra=calculation_log_extra(
            run_id=run_id,
            desk_id=desk_id,
            regime=policy.regime.value,
            total_ses=result.total_ses,
            type_a_count=aggregation.type_a_count,
            type_b_count=aggregation.type_b_count,
            ses_risk_factor_count=len(routing.ses_risk_factors),
            imcc_risk_factor_count=len(routing.imcc_risk_factors),
        ),
    )
    return result
