"""NMRF SES record types and validation helpers."""

from __future__ import annotations

import math
import warnings
from collections.abc import Sequence
from dataclasses import dataclass
from enum import StrEnum

import numpy as np
import numpy.typing as npt
from frtb_common import CalculationScope

from frtb_ima.data_models import LiquidityHorizon
from frtb_ima.org_scope import add_scope_payload, validate_scope_metadata


class NMRFStressMethod(StrEnum):
    """Method used to produce an individual NMRF stress scenario SES value."""

    LINEAR_SENSITIVITY = "LINEAR_SENSITIVITY"
    DIRECT = "DIRECT"
    STEPWISE = "STEPWISE"
    FULL_REVALUATION = "FULL_REVALUATION"
    MAX_LOSS_FALLBACK = "MAX_LOSS_FALLBACK"


_UNSUPPORTED_GENERATION_FEATURES: dict[NMRFStressMethod, str] = {
    NMRFStressMethod.DIRECT: "nmrf_direct_stress_scenario_generation",
    NMRFStressMethod.STEPWISE: "nmrf_stepwise_stress_scenario_generation",
    NMRFStressMethod.FULL_REVALUATION: "nmrf_full_revaluation_stress_scenario_generation",
    NMRFStressMethod.MAX_LOSS_FALLBACK: "nmrf_max_loss_fallback_generation",
}

_NMRF_MINIMUM_LIQUIDITY_HORIZON = LiquidityHorizon.LH20
_NEGATIVE_LOSS_WARNING_THRESHOLD = 0.75


@dataclass(frozen=True)
class NMRFStressScenarioResult:
    """
    Individual NMRF stress scenario result consumed by SES aggregation.

    ``generated_by_prototype`` is retained for API compatibility and flags
    approximation-only artifacts generated by this package. Direct, stepwise,
    and full-revaluation losses must come from upstream stress artifacts rather
    than embedded pricing logic in this package.
    """

    risk_factor_name: str
    method: NMRFStressMethod
    ses: float
    generated_by_prototype: bool
    source: str = ""
    notes: str = ""
    org_scope: CalculationScope | None = None

    def __post_init__(self) -> None:
        if not self.risk_factor_name:
            raise ValueError("risk_factor_name must be non-empty")
        if not isinstance(self.method, NMRFStressMethod):
            raise TypeError("method must be an NMRFStressMethod")
        if not math.isfinite(self.ses) or self.ses < 0.0:
            raise ValueError(f"ses must be a non-negative finite value, got {self.ses}")
        object.__setattr__(
            self,
            "org_scope",
            validate_scope_metadata(
                self.org_scope,
                field="NMRFStressScenarioResult.org_scope",
            ),
        )

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails.
        Returns
        -------
        dict[str, object]
            Result of the operation.
        """
        return add_scope_payload(
            {
                "risk_factor_name": self.risk_factor_name,
                "method": self.method.value,
                "ses": self.ses,
                "generated_by_prototype": self.generated_by_prototype,
                "source": self.source,
                "notes": self.notes,
            },
            self.org_scope,
        )


@dataclass(frozen=True)
class NMRFStressArtifact:
    """
    Post-valuation NMRF stress output consumed by the capital layer.

    The capital layer does not price trades. It validates and consumes loss
    vectors produced by an upstream valuation run under the selected NMRF stress
    method. Values use the package loss convention: positive means loss,
    negative means gain.
    """

    risk_factor_name: str
    method: NMRFStressMethod
    losses: npt.NDArray[np.float64] | Sequence[float]
    liquidity_horizon: LiquidityHorizon
    stress_period: str
    source: str
    scenario_ids: tuple[str, ...] = ()
    generated_by_prototype: bool = False
    notes: str = ""
    org_scope: CalculationScope | None = None

    def __post_init__(self) -> None:
        if not self.risk_factor_name:
            raise ValueError("risk_factor_name must be non-empty")
        if not isinstance(self.method, NMRFStressMethod):
            raise TypeError("method must be an NMRFStressMethod")
        if not isinstance(self.liquidity_horizon, LiquidityHorizon):
            raise TypeError("liquidity_horizon must be a LiquidityHorizon")
        if self.liquidity_horizon.value < _NMRF_MINIMUM_LIQUIDITY_HORIZON.value:
            raise ValueError("NMRF liquidity_horizon must be at least 20 business days")
        if not self.stress_period:
            raise ValueError("stress_period must be non-empty")
        if not self.source:
            raise ValueError("source must be non-empty")

        losses = _as_loss_array(self.losses, "losses")
        negative_fraction = float(np.mean(losses < 0.0))
        if negative_fraction > _NEGATIVE_LOSS_WARNING_THRESHOLD:
            warnings.warn(
                f"NMRFStressArtifact for {self.risk_factor_name}: "
                f"{negative_fraction:.0%} of loss values are negative. "
                "Sign convention is positive=loss. If using gains convention "
                "(positive=profit), negate the vector before constructing this artifact.",
                UserWarning,
                stacklevel=2,
            )
        scenario_ids = tuple(self.scenario_ids)
        if scenario_ids:
            if len(scenario_ids) != losses.size:
                raise ValueError("scenario_ids length must match losses length")
            if any(not scenario_id for scenario_id in scenario_ids):
                raise ValueError("scenario_ids cannot contain empty values")
            if len(scenario_ids) != len(set(scenario_ids)):
                raise ValueError("scenario_ids contains duplicates")

        object.__setattr__(self, "losses", losses)
        object.__setattr__(self, "scenario_ids", scenario_ids)
        object.__setattr__(
            self,
            "org_scope",
            validate_scope_metadata(self.org_scope, field="NMRFStressArtifact.org_scope"),
        )

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable audit summary without expanding the loss vector.
        Returns
        -------
        dict[str, object]
            Result of the operation.
        """
        return add_scope_payload(
            {
                "risk_factor_name": self.risk_factor_name,
                "method": self.method.value,
                "loss_count": int(np.asarray(self.losses).size),
                "liquidity_horizon": self.liquidity_horizon.value,
                "stress_period": self.stress_period,
                "source": self.source,
                "scenario_ids": list(self.scenario_ids),
                "generated_by_prototype": self.generated_by_prototype,
                "notes": self.notes,
            },
            self.org_scope,
        )


@dataclass(frozen=True)
class SESAggregationResult:
    """Audit-friendly decomposition of NMRF SES aggregation."""

    type_a_count: int
    type_b_count: int
    type_a_sum_of_squares: float
    type_b_correlated_term: float
    type_b_sum_of_squares: float
    type_b_linear_sum: float
    type_b_rho: float
    total_ses: float

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails.
        Returns
        -------
        dict[str, object]
            Result of the operation.
        """
        return {
            "type_a_count": self.type_a_count,
            "type_b_count": self.type_b_count,
            "type_a_sum_of_squares": self.type_a_sum_of_squares,
            "type_b_correlated_term": self.type_b_correlated_term,
            "type_b_sum_of_squares": self.type_b_sum_of_squares,
            "type_b_linear_sum": self.type_b_linear_sum,
            "type_b_rho": self.type_b_rho,
            "total_ses": self.total_ses,
        }


@dataclass(frozen=True)
class NMRFCapitalRouting:
    """Risk-factor routing implied by Fed NPR 2.0 Type A / Type B treatment."""

    modellable_risk_factors: tuple[str, ...]
    type_a_nmrf_risk_factors: tuple[str, ...]
    type_b_nmrf_risk_factors: tuple[str, ...]
    imcc_risk_factors: tuple[str, ...]
    ses_risk_factors: tuple[str, ...]

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails.
        Returns
        -------
        dict[str, object]
            Result of the operation.
        """
        return {
            "modellable_risk_factors": list(self.modellable_risk_factors),
            "type_a_nmrf_risk_factors": list(self.type_a_nmrf_risk_factors),
            "type_b_nmrf_risk_factors": list(self.type_b_nmrf_risk_factors),
            "imcc_risk_factors": list(self.imcc_risk_factors),
            "ses_risk_factors": list(self.ses_risk_factors),
        }


@dataclass(frozen=True)
class NMRFCapitalResult:
    """NMRF SES result with routing and aggregation audit detail."""

    routing: NMRFCapitalRouting
    type_a_results: tuple[NMRFStressScenarioResult, ...]
    type_b_results: tuple[NMRFStressScenarioResult, ...]
    aggregation: SESAggregationResult

    @property
    def total_ses(self) -> float:
        """Total SES scalar used by the models-based capital formula.
        Returns
        -------
        float
            Result of the operation.
        """
        return self.aggregation.total_ses

    def as_dict(self) -> dict[str, object]:
        """Return a serialisable dictionary for reporting and audit trails.
        Returns
        -------
        dict[str, object]
            Result of the operation.
        """
        return {
            "routing": self.routing.as_dict(),
            "type_a_results": [result.as_dict() for result in self.type_a_results],
            "type_b_results": [result.as_dict() for result in self.type_b_results],
            "aggregation": self.aggregation.as_dict(),
            "total_ses": self.total_ses,
        }


def _as_loss_array(
    values: Sequence[float] | npt.NDArray[np.float64],
    name: str,
) -> npt.NDArray[np.float64]:
    arr = np.asarray(values, dtype=float)
    if arr.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")
    if arr.size == 0:
        raise ValueError(f"{name} must be non-empty")
    if not np.all(np.isfinite(arr)):
        raise ValueError(f"{name} must contain only finite values")
    result = arr.astype(np.float64, copy=True)
    result.flags.writeable = False
    return result


__all__ = [
    "NMRFCapitalResult",
    "NMRFCapitalRouting",
    "NMRFStressArtifact",
    "NMRFStressMethod",
    "NMRFStressScenarioResult",
    "SESAggregationResult",
]
