"""Shared primitives for the frtb-capital suite."""

from frtb_common._version import __version__
from frtb_common.arrow_conversion import (
    arrow_bool_array,
    arrow_bool_or_object_array,
    arrow_float64_array,
    arrow_float64_array_with_nulls,
    arrow_object_array,
    read_handoff_columns,
)
from frtb_common.attribution import (
    AttributionMethod,
    CapitalContribution,
)
from frtb_common.batch_arrays import (
    BatchArrayCoercionError,
    bool_array,
    coerce_bool_value,
    float_array_from_numpy,
    immutable_float_array,
    immutable_object_array,
    object_array,
    optional_bool_object_array,
    readonly_array,
)
from frtb_common.component_handoff import (
    ComponentHandoffError,
    ComponentResultHandoff,
    StandardisedComponent,
)
from frtb_common.crif import (
    CRIF_RISK_TYPE_COLUMN,
    CRIF_SOURCE_ROW_ID_COLUMN,
    CRIF_SOURCE_SYSTEM,
    DEFAULT_CRIF_COLUMN_SPECS,
    CrifColumnSpec,
    CrifRiskTypeMapper,
    CrifRiskTypeMapping,
    crif_records_to_arrow_table,
    normalise_crif_risk_type,
    normalize_crif_arrow_table,
    normalize_crif_records,
    resolve_crif_column_name,
)
from frtb_common.handoff import (
    DEFAULT_ROW_ID_COLUMN,
    AdapterDiagnostic,
    ChunkPolicy,
    ColumnSpec,
    DiagnosticSeverity,
    DictionaryPolicy,
    NormalizedTabularHandoff,
    NullPolicy,
    TabularHandoffError,
    TabularLogicalType,
    arrow_table_content_hash,
    dictionary_code_chunks,
    dictionary_code_column,
    normalize_arrow_table,
    normalized_handoff_hash,
    resolve_column_name,
    sort_table_by_columns,
    source_content_hash,
    validate_arrow_table,
    validate_column_specs,
)
from frtb_common.hashing import (
    is_sha256_hex,
    require_sha256_hex,
    stable_json_dumps,
    stable_json_hash,
)
from frtb_common.regulatory import (
    MissingRegulatoryCitationsError,
    assert_policy_has_regulatory_citations,
)
from frtb_common.serialization import jsonable
from frtb_common.status import (
    CapitalComponentMetadata,
    ImplementationStatus,
    NotImplementedCapitalComponentError,
    UnsupportedRegulatoryFeatureError,
    ValidationStatus,
)

__all__ = [
    "CRIF_RISK_TYPE_COLUMN",
    "CRIF_SOURCE_ROW_ID_COLUMN",
    "CRIF_SOURCE_SYSTEM",
    "DEFAULT_CRIF_COLUMN_SPECS",
    "DEFAULT_ROW_ID_COLUMN",
    "AdapterDiagnostic",
    "AttributionMethod",
    "BatchArrayCoercionError",
    "CapitalComponentMetadata",
    "CapitalContribution",
    "ChunkPolicy",
    "ColumnSpec",
    "ComponentHandoffError",
    "ComponentResultHandoff",
    "CrifColumnSpec",
    "CrifRiskTypeMapper",
    "CrifRiskTypeMapping",
    "DiagnosticSeverity",
    "DictionaryPolicy",
    "ImplementationStatus",
    "MissingRegulatoryCitationsError",
    "NormalizedTabularHandoff",
    "NotImplementedCapitalComponentError",
    "NullPolicy",
    "StandardisedComponent",
    "TabularHandoffError",
    "TabularLogicalType",
    "UnsupportedRegulatoryFeatureError",
    "ValidationStatus",
    "__version__",
    "arrow_bool_array",
    "arrow_bool_or_object_array",
    "arrow_float64_array",
    "arrow_float64_array_with_nulls",
    "arrow_object_array",
    "arrow_table_content_hash",
    "assert_policy_has_regulatory_citations",
    "bool_array",
    "coerce_bool_value",
    "crif_records_to_arrow_table",
    "dictionary_code_chunks",
    "dictionary_code_column",
    "float_array_from_numpy",
    "immutable_float_array",
    "immutable_object_array",
    "is_sha256_hex",
    "jsonable",
    "normalise_crif_risk_type",
    "normalize_arrow_table",
    "normalize_crif_arrow_table",
    "normalize_crif_records",
    "normalized_handoff_hash",
    "object_array",
    "optional_bool_object_array",
    "read_handoff_columns",
    "readonly_array",
    "require_sha256_hex",
    "resolve_column_name",
    "resolve_crif_column_name",
    "sort_table_by_columns",
    "source_content_hash",
    "stable_json_dumps",
    "stable_json_hash",
    "validate_arrow_table",
    "validate_column_specs",
]
