"""Compatibility exports for SBM rule-profile reference data.

Regulatory traceability:
    See docs/REGULATORY_TRACEABILITY.md rows for reference_data.py, Basel
    MAR21.38-MAR21.43, and SBM-REF-001.
"""

from __future__ import annotations

from frtb_sbm.commodity_reference_data import (
    commodity_bucket_definition,
    commodity_buckets_for_profile,
    commodity_delta_intra_bucket_correlation,
    commodity_delta_risk_weight,
    commodity_inter_bucket_correlation,
)
from frtb_sbm.csr_nonsec_reference_data import (
    csr_nonsec_bucket_definition,
    csr_nonsec_buckets_for_profile,
    csr_nonsec_delta_intra_bucket_correlation,
    csr_nonsec_delta_risk_weight,
    csr_nonsec_inter_bucket_correlation,
    csr_nonsec_validate_delta_inputs,
    csr_nonsec_validate_vega_inputs,
)
from frtb_sbm.curvature_reference_data import curvature_citation_ids, curvature_risk_weight
from frtb_sbm.equity_reference_data import (
    equity_bucket_definition,
    equity_buckets_for_profile,
    equity_delta_intra_bucket_correlation,
    equity_delta_risk_weight,
    equity_inter_bucket_correlation,
)
from frtb_sbm.fx_reference_data import (
    BASEL_FX_BUCKETS,
    BASEL_FX_SPECIFIED_CURRENCIES,
    FX_DELTA_RISK_WEIGHT,
    FX_INTER_BUCKET_CORRELATION,
    FX_INTRA_BUCKET_CORRELATION,
    fx_bucket_definition,
    fx_buckets_for_profile,
    fx_delta_intra_bucket_correlation,
    fx_delta_risk_weight,
    fx_inter_bucket_correlation,
    fx_specified_currencies_for_profile,
    normalise_fx_delta_currency_code,
)
from frtb_sbm.girr_reference_correlations import (
    girr_delta_intra_bucket_correlation,
    girr_inter_bucket_correlation,
)
from frtb_sbm.girr_reference_data import (
    BASEL_GIRR_BUCKETS,
    BASEL_GIRR_DELTA_RISK_WEIGHTS,
    BASEL_GIRR_SPECIAL_RISK_FACTORS,
    BASEL_GIRR_TENORS,
    GIRR_DELTA_INTRA_BUCKET_CONSTANT,
    GIRR_DIFFERENT_CURVE_CORRELATION,
    GIRR_INFLATION_DIFFERENT_TENOR_CORRELATION,
    GIRR_INFLATION_SAME_TENOR_CORRELATION,
    GIRR_INTER_BUCKET_CORRELATION,
    GIRR_INTRA_BUCKET_CORRELATION_FLOOR,
    GIRR_SAME_CURVE_CORRELATION,
    LIQUID_GIRR_CURRENCIES,
    girr_bucket_definition,
    girr_bucket_for_currency,
    girr_buckets_for_profile,
    girr_delta_risk_weight,
    girr_delta_risk_weight_rule,
    girr_tenor_definition,
    girr_tenors_for_profile,
)
from frtb_sbm.reference_payload import profile_reference_payload
from frtb_sbm.reference_profiles import (
    BASEL_CORRELATION_SCENARIOS,
    apply_correlation_scenario,
    apply_correlation_scenario_definition,
    citations_for_profile,
    correlation_scenario_definition,
    correlation_scenarios_for_profile,
)
from frtb_sbm.reference_types import (
    SbmCorrelationScenarioDefinition,
    SbmFxBucketDefinition,
    SbmGirrBucketDefinition,
    SbmGirrRiskWeightRule,
    SbmGirrSpecialRiskFactorRule,
    SbmGirrTenorDefinition,
)
from frtb_sbm.vega_reference_data import (
    GIRR_VEGA_INTRA_BUCKET_CONSTANT,
    GIRR_VEGA_RISK_WEIGHT_CAP,
    GIRR_VEGA_RISK_WEIGHT_FACTOR,
    PROFILE_GIRR_VEGA_LIQUIDITY_HORIZON_DAYS,
    PROFILE_VEGA_LIQUIDITY_HORIZON_DAYS,
    girr_vega_intra_bucket_correlation,
    girr_vega_liquidity_horizon_days,
    girr_vega_option_tenor_definition,
    girr_vega_option_tenors,
    vega_inter_bucket_citation_ids,
    vega_intra_bucket_citation_ids,
    vega_liquidity_horizon_days,
    vega_option_tenor_correlation,
    vega_risk_weight,
    vega_scenario_citation_ids,
)

__all__ = [
    "BASEL_CORRELATION_SCENARIOS",
    "BASEL_FX_BUCKETS",
    "BASEL_FX_SPECIFIED_CURRENCIES",
    "BASEL_GIRR_BUCKETS",
    "BASEL_GIRR_DELTA_RISK_WEIGHTS",
    "BASEL_GIRR_SPECIAL_RISK_FACTORS",
    "BASEL_GIRR_TENORS",
    "FX_DELTA_RISK_WEIGHT",
    "FX_INTER_BUCKET_CORRELATION",
    "FX_INTRA_BUCKET_CORRELATION",
    "GIRR_DELTA_INTRA_BUCKET_CONSTANT",
    "GIRR_DIFFERENT_CURVE_CORRELATION",
    "GIRR_INFLATION_DIFFERENT_TENOR_CORRELATION",
    "GIRR_INFLATION_SAME_TENOR_CORRELATION",
    "GIRR_INTER_BUCKET_CORRELATION",
    "GIRR_INTRA_BUCKET_CORRELATION_FLOOR",
    "GIRR_SAME_CURVE_CORRELATION",
    "GIRR_VEGA_INTRA_BUCKET_CONSTANT",
    "GIRR_VEGA_RISK_WEIGHT_CAP",
    "GIRR_VEGA_RISK_WEIGHT_FACTOR",
    "LIQUID_GIRR_CURRENCIES",
    "PROFILE_GIRR_VEGA_LIQUIDITY_HORIZON_DAYS",
    "PROFILE_VEGA_LIQUIDITY_HORIZON_DAYS",
    "SbmCorrelationScenarioDefinition",
    "SbmFxBucketDefinition",
    "SbmGirrBucketDefinition",
    "SbmGirrRiskWeightRule",
    "SbmGirrSpecialRiskFactorRule",
    "SbmGirrTenorDefinition",
    "apply_correlation_scenario",
    "apply_correlation_scenario_definition",
    "citations_for_profile",
    "commodity_bucket_definition",
    "commodity_buckets_for_profile",
    "commodity_delta_intra_bucket_correlation",
    "commodity_delta_risk_weight",
    "commodity_inter_bucket_correlation",
    "correlation_scenario_definition",
    "correlation_scenarios_for_profile",
    "csr_nonsec_bucket_definition",
    "csr_nonsec_buckets_for_profile",
    "csr_nonsec_delta_intra_bucket_correlation",
    "csr_nonsec_delta_risk_weight",
    "csr_nonsec_inter_bucket_correlation",
    "csr_nonsec_validate_delta_inputs",
    "csr_nonsec_validate_vega_inputs",
    "curvature_citation_ids",
    "curvature_risk_weight",
    "equity_bucket_definition",
    "equity_buckets_for_profile",
    "equity_delta_intra_bucket_correlation",
    "equity_delta_risk_weight",
    "equity_inter_bucket_correlation",
    "fx_bucket_definition",
    "fx_buckets_for_profile",
    "fx_delta_intra_bucket_correlation",
    "fx_delta_risk_weight",
    "fx_inter_bucket_correlation",
    "fx_specified_currencies_for_profile",
    "girr_bucket_definition",
    "girr_bucket_for_currency",
    "girr_buckets_for_profile",
    "girr_delta_intra_bucket_correlation",
    "girr_delta_risk_weight",
    "girr_delta_risk_weight_rule",
    "girr_inter_bucket_correlation",
    "girr_tenor_definition",
    "girr_tenors_for_profile",
    "girr_vega_intra_bucket_correlation",
    "girr_vega_liquidity_horizon_days",
    "girr_vega_option_tenor_definition",
    "girr_vega_option_tenors",
    "normalise_fx_delta_currency_code",
    "profile_reference_payload",
    "vega_inter_bucket_citation_ids",
    "vega_intra_bucket_citation_ids",
    "vega_liquidity_horizon_days",
    "vega_option_tenor_correlation",
    "vega_risk_weight",
    "vega_scenario_citation_ids",
]
