"""Suite-level orchestration scaffold."""

from frtb_common import ComponentCapitalSummary, StandardisedComponent

from frtb_orchestration._version import __version__
from frtb_orchestration.artifact_evidence import (
    ArtifactEvidenceKind,
    ArtifactEvidenceRef,
    ArtifactEvidenceStatus,
    ComponentArtifactEvidence,
    SuiteArtifactEvidenceView,
    SuiteEvidenceComponent,
    build_suite_artifact_evidence_view,
)
from frtb_orchestration.artifact_evidence_inputs import (
    ImaScenarioEvidence,
    SbmShockEvidence,
    SurfaceEvidence,
    TimelineEvidence,
)
from frtb_orchestration.cva_summary import (
    CvaCapitalSummary,
    recognise_cva_summary,
)
from frtb_orchestration.ima_summary import (
    ImaCapitalSummary,
    recognise_ima_summary,
)
from frtb_orchestration.manifest import (
    CVA_COUNTERPARTY_INPUT_TABLE,
    CVA_HEDGE_INPUT_TABLE,
    CVA_NETTING_SET_INPUT_TABLE,
    CVA_SA_SENSITIVITY_INPUT_TABLE,
    DRC_CTP_INPUT_TABLE,
    DRC_NONSEC_INPUT_TABLE,
    DRC_SECURITISATION_NON_CTP_INPUT_TABLE,
    RRAO_POSITIONS_INPUT_TABLE,
    SBM_GIRR_DELTA_INPUT_TABLE,
    STANDARDISED_REQUIRED_INPUT_TABLE_KEYS,
    CapitalRunManifest,
    ManifestInputTableRoute,
    ManifestInputTableValidation,
    ManifestValidationResult,
    SaManifestRunResult,
    run_standardised_approach_from_manifest,
    validate_capital_run_manifest,
)
from frtb_orchestration.resolved_artifact_evidence import (
    build_ima_scenario_evidence_refs,
    build_resolved_artifact_evidence_view,
    build_sbm_shock_evidence_refs,
    build_surface_evidence_refs,
    build_timeline_evidence_refs,
)
from frtb_orchestration.risk_factor_views import (
    RiskFactorAggregateView,
    RiskFactorCapitalViewRow,
    RiskFactorEvidenceViewRow,
    RiskFactorViewStatus,
    build_risk_factor_aggregate_view,
)
from frtb_orchestration.scaffold import (
    PACKAGE_METADATA,
    aggregate_suite_attribution,
    build_suite_attribution_report,
    calculate_suite_capital,
)
from frtb_orchestration.scope_views import (
    BindingCapitalResult,
    BindingCapitalSide,
    ScopeCapitalView,
    ScopeComponentCapital,
    ScopeViewStatus,
    compose_scope_capital_view,
)
from frtb_orchestration.standardised import (
    OrchestrationInputError,
    StandardisedApproachCapitalResult,
    StandardisedComponentSubtotal,
    StandardisedFallbackRoute,
    compose_standardised_approach_capital,
    standardised_jurisdiction_family,
)
from frtb_orchestration.suite import (
    SuiteAttributionComponentReport,
    SuiteAttributionReport,
    SuiteAttributionResult,
    SuiteCapitalResult,
    suite_jurisdiction_family,
)
from frtb_orchestration.suite_attribution_summary import (
    SuiteAttributionGroupSummary,
    SuiteAttributionRecordSummary,
    SuiteAttributionSummary,
    suite_attribution_residual_records,
    suite_attribution_unsupported_records,
    summarise_suite_attribution,
    top_suite_attribution_contributors,
)

__all__ = [
    "CVA_COUNTERPARTY_INPUT_TABLE",
    "CVA_HEDGE_INPUT_TABLE",
    "CVA_NETTING_SET_INPUT_TABLE",
    "CVA_SA_SENSITIVITY_INPUT_TABLE",
    "DRC_CTP_INPUT_TABLE",
    "DRC_NONSEC_INPUT_TABLE",
    "DRC_SECURITISATION_NON_CTP_INPUT_TABLE",
    "PACKAGE_METADATA",
    "RRAO_POSITIONS_INPUT_TABLE",
    "SBM_GIRR_DELTA_INPUT_TABLE",
    "STANDARDISED_REQUIRED_INPUT_TABLE_KEYS",
    "ArtifactEvidenceKind",
    "ArtifactEvidenceRef",
    "ArtifactEvidenceStatus",
    "BindingCapitalResult",
    "BindingCapitalSide",
    "CapitalRunManifest",
    "ComponentArtifactEvidence",
    "ComponentCapitalSummary",
    "CvaCapitalSummary",
    "ImaCapitalSummary",
    "ImaScenarioEvidence",
    "ManifestInputTableRoute",
    "ManifestInputTableValidation",
    "ManifestValidationResult",
    "OrchestrationInputError",
    "RiskFactorAggregateView",
    "RiskFactorCapitalViewRow",
    "RiskFactorEvidenceViewRow",
    "RiskFactorViewStatus",
    "SaManifestRunResult",
    "SbmShockEvidence",
    "ScopeCapitalView",
    "ScopeComponentCapital",
    "ScopeViewStatus",
    "StandardisedApproachCapitalResult",
    "StandardisedComponent",
    "StandardisedComponentSubtotal",
    "StandardisedFallbackRoute",
    "SuiteArtifactEvidenceView",
    "SuiteAttributionComponentReport",
    "SuiteAttributionGroupSummary",
    "SuiteAttributionRecordSummary",
    "SuiteAttributionReport",
    "SuiteAttributionResult",
    "SuiteAttributionSummary",
    "SuiteCapitalResult",
    "SuiteEvidenceComponent",
    "SurfaceEvidence",
    "TimelineEvidence",
    "__version__",
    "aggregate_suite_attribution",
    "build_ima_scenario_evidence_refs",
    "build_resolved_artifact_evidence_view",
    "build_risk_factor_aggregate_view",
    "build_sbm_shock_evidence_refs",
    "build_suite_artifact_evidence_view",
    "build_suite_attribution_report",
    "build_surface_evidence_refs",
    "build_timeline_evidence_refs",
    "calculate_suite_capital",
    "compose_scope_capital_view",
    "compose_standardised_approach_capital",
    "recognise_cva_summary",
    "recognise_ima_summary",
    "run_standardised_approach_from_manifest",
    "standardised_jurisdiction_family",
    "suite_attribution_residual_records",
    "suite_attribution_unsupported_records",
    "suite_jurisdiction_family",
    "summarise_suite_attribution",
    "top_suite_attribution_contributors",
    "validate_capital_run_manifest",
]
